### ISSUE TITLE
能不能加一个随机播放的功能

### ISSUE THREAD

**Issue by bai0012** [kikoeru-project/kikoeru-express#1]
音声太多，随机播放找点新鲜感，要不然整体都只听刚刚下载的，之前的就忘记了

**Comment by umonaca** [comment]
emmmm可以。是随机选择一部作品播放，还是随机从不同的作品里各挑一个文件然后随机串烧下去？
听音声和听歌还是不太一样的，同一部有剧情上的连续性。

**Comment by bai0012** [comment]
> emmmm可以。是随机选择一部作品播放，还是随机从不同的作品里各挑一个文件然后随机串烧下去？
> 听音声和听歌还是不太一样的，同一部有剧情上的连续性。

是随机挑一部音声放，里面的顺序再打乱了就不太好了，咋说呢，就跟抽奖抽音声一样
哦对，要是能加上在具体范围里抽就好了
比如说在R18作品里抽取，在社团里抽取之类的

**Comment by umonaca** [comment]
v0.5.0已解决。增加随心听功能（左侧边栏）和随机排序功能。
