### ISSUE TITLE
添加RJ305000时出现错误

### ISSUE THREAD

**Issue by yyxida** [kikoeru-project/kikoeru-express#12]
添加RJ305000时出现错误
版本为v0.5.2，运行环境为群晖Docker

另外非常感谢维护更新

> ➜ 发现新文件夹: "/usr/src/kikoeru/Folders/VoiceWork/【TS百合】先輩が私だけに教えてくれた百合の秘密【バイノーラル】 RJ305000"
➜ 从 DLSite 抓取元数据...
➜ 元数据抓取成功，准备添加到数据库...
➜ 在插入元数据过程中出错: insert into `t_work` (`circle_id`, `dir`, `dl_count`, `id`, `nsfw`, `price`, `rank`, `rate_average_2dp`, `rate_count`, `rate_count_detail`, `release`, `review_count`, `root_folder`, `title`) values (4303, '【TS百合】先輩が私だけに教えてくれた百合の秘密【バイノーラル】 RJ305000', '24', 305000, true, 990, NULL, NULL, NULL, '[]', '2021-01-28', 0, '音声', '生意気ギャル妹とヒミツの関係☆-童貞アニキに女の子を教えてあげる-') - SQLITE_CONSTRAINT: NOT NULL constraint failed: t_work.rate_count
➜ 添加失败! Failed: 1

**Comment by yyxida** [comment]
重新创建了几次Docker，最后发现是RJ号弄错了，非常抱歉打扰了。

**Comment by umonaca** [comment]
虽然起因是RJ号写错了，但是您提的问题是一个好问题。您发issue的时候RJ305000还没有发售，所以爬不到相应的评价数据；然而上游在schema里面加了太多NOT NULL限制，导致只要有一个爬不到内容就添加失败。
由于需要调整的地方比较多，我打算在0.6.0的时候修复这个问题。不过这个问题一般用户是遇不到的。
