### ISSUE TITLE
添加 RJ311747 后除封面外无其他任何元数据

### ISSUE THREAD

**Issue by ShadowLyin** [kikoeru-project/kikoeru-express#13]
本地系统: Windows 10 20H2 专业版

软件版本: 0.5.4-win-x64 (使用 pm2 启动)

问题描述：添加 RJ311747 后，在主界面只能显示出封面，没有显示标题等其他信息（见截图 1），进入这部作品之后，弹出消息提示 ”There is no work with id 311747 in the database.“，但能正常显示文件（见截图 2） 。已经尝试删除作品重新添加以及更换元数据语言，都没有用。其他同一时间添加的作品正常。

截图：
![image](https://user-images.githubusercontent.com/20549332/106171318-5b6c9f00-61cc-11eb-98ec-7abbad3cfe1a.png)
![image](https://user-images.githubusercontent.com/20549332/106171545-9cfd4a00-61cc-11eb-9f65-33e642bfb1e9.png)

**Comment by umonaca** [comment]
这是一个没有标签的作品，所以读取的时候查询挂了。不需要担心数据库，里面数据都是正常的。一会儿我修一下。
