### ISSUE TITLE
好像不能扫描局域网里其他电脑的音声

### ISSUE THREAD

**Issue by bai0012** [kikoeru-project/kikoeru-express#14]
添加了诸如这种的地址"\\\Desktop-7idsius\d\ASMR"
然后点扫描，就没动静了
本地的是正常的
就卡到这里了
![image](https://user-images.githubusercontent.com/53823526/106223095-bf6a8400-621b-11eb-8f3d-9cb232256d1d.png)

**Comment by bai0012** [comment]
啊，好了好了，只是反应慢了一点，等了一个小时已经扫完了

**Comment by umonaca** [comment]
此程序不是为Windows下的远程文件夹设计的。本地的话上百部也只需要十几秒到几十秒爬完。使用Windows下远程文件夹的话，建议映射驱动器，那样会快很多。
