### ISSUE TITLE
版本升级后，数据库丢失

### ISSUE THREAD

**Issue by Rin-imas** [kikoeru-project/kikoeru-express#19]
老哥你好。
        由于我之前是从v0.3.0的版本升级到V0.5.6，当时不知道如何做数据迁移，只能重新扫描添加。
今天，看到v0.5.7更新，就在上午的时候把v0.5.6的 config、sqlite、covers三个文件夹复制了过来，并在设置里面更改了封面储存的地方。上午使用v0.5.7的时候，一切正常。下午再次使用，cmd里面显示成功构建了数据库，这个时候登陆localhost界面，所有的作品已消失，又不得不重新扫描添加。
       想问下老哥现在版本的数据迁移该怎么做？谢谢老哥。

**Comment by umonaca** [comment]
现在的数据库迁移是全自动并且向下兼容的。即使有bug我也会在新版里写好修复脚本。
不要直接复制数据文件。可以直接覆盖，或者把新版主程序和旧版放在同一个目录内，或者如果是Docker版那么直接挂载同样的文件夹。不放心可以备份一下。

至于不直接复制数据文件的原因：
你可以打开`config/config.json`，里面`databaseFolderDir`是数据库位置。这个地方是**绝对路径**而不是**相对路径**，格式取决于你使用什么操作系统，还有就是Docker还是win-x64版。如果你复制了以后**这个地方没有改对位置**，比方说，它还是指向旧版那个位置的数据库文件，虽然当时并不会有什么后果，但是比如你下午的时候把旧版数据库文件所在的移动硬盘拔掉了，那会发生什么我也不是很清楚……
还有注意Docker版和win-x64版配置文件（config.json）互不兼容，因为一个是Windows路径格式一个是Linux路径格式，需要手动改。

如果以上说明没有解决你的问题，请贴一下
- 你的`config.json`
- Docker版还是Windows版还是源码安装
- 如果是源码安装，那么操作系统是什么
- 请直接在系统里搜索一下`db.sqlite3`文件，应该会有两个以上，它们分别出现在了什么位置

**Comment by umonaca** [comment]
从v0.3.0升级v0.5.6也是一样的，数据库迁移是全自动并且向下兼容的。目前的版本号是按semantic versioning来的，也就是
`不兼容的更新 . 兼容的更新 . 修复补丁`
这样的格式。只要最大的版本号不改，那么升级就是兼容并且自动的。

对于你遇到的情况，我的判断是**数据库文件并没有丢失**，而是由于各种各样的原因，使得你两次打开程序所使用的**数据库文件不同**。你可以**直接搜索一下**`db.sqlite3`文件，应该可以得到答案。并不存在覆盖掉或者破坏的可能。
我个人比较经常遇到的是调试Docker版路径没挂载对的时候就会这样，还有就是Docker和win版混用忘了改`config.json`的时候也会。结果都是存在了别的位置而已，具体不展开了。

**Comment by umonaca** [comment]
我想了一下，这是个好问题。上游没有考虑程序搬家或者比如移动硬盘驱动器号变化之类的情况，设置里使用绝对路径是有隐患的。

**Comment by Rin-imas** [comment]
感谢老哥，我不太懂编程方面。这个问题应该是数据库的绝对路径造成的，下午的时候，删除了v0.5.6的所有文件，由此再次打开v0.5.7版本出现了构建数据库的提示。

**Comment by umonaca** [comment]
> 感谢老哥，我不太懂编程方面。这个问题应该是数据库的绝对路径造成的，下午的时候，删除了v0.5.6的所有文件，由此再次打开v0.5.7版本出现了构建数据库的提示。

对。由于你的config.json设置里面数据库仍然指向原来的位置，下午的时候删除了旧版，那么数据库就"没有了”，于是就出现了你说的情况。如果你手动改一下config.json里面的设置改成新的路径，那么你应该可以看到原来的东西（打星、标记等等）。
下个版本考虑加上相对路径功能，这样程序就可以随意移动不出错了。
