### ISSUE TITLE
[Bug] Mac OS版兼容性问题

### ISSUE THREAD

**Issue by shawncafu** [kikoeru-project/kikoeru-express#24]
➜ 发现新文件夹: "/Volumes/好物坚牢/VOICE/VoiceWork/RJ314382"
➜ 从 DLSite 抓取元数据...
➜ 元数据抓取成功，准备添加到数据库...
➜ 在插入元数据过程中出错: insert or ignore into `t_va` (`id`, `name`) values ('72c29581-496f-593e-871e-71bf1a2084e2', '来夢ふらん') - SQLITE_MISMATCH: datatype mismatch
➜ 添加失败! Failed: 1

Mac 0.6.0RC3

**Comment by shawncafu** [comment]
是从RC0直接覆盖上来的，我删掉库重新试一下
直接用RC3扫描成功了，没这个问题orz

**Comment by umonaca** [comment]
手上并没有任何苹果设备，虚拟机里跑Mac极其卡顿，硬件不支持搞不了黑苹果，所以调试得不彻底。

- 刚才测试中发现从终端运行和从Finder里面双击运行的结果是完全不一样的，没想到Mac上从Finder里双击打开的话当前工作目录并不是程序所在目录而是`/Users/your_user_name`。

- Mac上的权限拦截可能会造成不确定的结果。我得想想这个问题该怎么解决。
- 不打算考虑M1 rosetta兼容性，因为没有M1。

修起来需要一点时间。不同版本稳定性：Windows版 > Docker版 > Mac版，讨厌遇到Mac版bug的话可以用Docker版。

**Comment by umonaca** [comment]
我觉得这个问题解决起来非常恶心，依用户操作不同至少有三种以上不同的状态。

**Comment by shawncafu** [comment]
不好意思我之前描述的不太详尽
因为后来没有覆盖，用RC3解压直接重新扫描一遍没有问题我就没再继续测试了
我是M1，直接把RC3拖进RC0然后做的替换，之后双击运行的，当时也只有这一个报错，其他新增都成功

毕竟直接安装可以用，我有时也喜欢自己删库重新扫描，这个这么恶心的话干脆别修了，先考虑其他更新吧

**Comment by umonaca** [comment]
> 不好意思我之前描述的不太详尽
> 因为后来没有覆盖，用RC3解压直接重新扫描一遍没有问题我就没再继续测试了
> 我是M1，直接把RC3拖进RC0然后做的替换，之后双击运行的，当时也只有这一个报错，其他新增都成功
> 
> 毕竟直接安装可以用，我有时也喜欢自己删库重新扫描，这个这么恶心的话干脆别修了，先考虑其他更新吧

刚发布的新版里应该解决了。如果有其它问题可以报一下。
