### ISSUE TITLE
[Feature request]同屏显示更多音声作品

### ISSUE THREAD

**Issue by shawncafu** [kikoeru-project/kikoeru-express#25]
现在最多同时显示四列，能否增加一下列数，比如同时显示六列，七列？
或者像DL Play一样仅显示封面，不显示其他信息，这样同屏能显示几十个音声作品，方便挑选

**Comment by umonaca** [comment]
> 现在最多同时显示四列，能否增加一下列数，比如同时显示六列，七列？
> 或者像DL Play一样仅显示封面，不显示其他信息，这样同屏能显示几十个音声作品，方便挑选

列表模式，图中顶部正中央的按钮。如果觉得乱，列表模式下右上角按钮可以隐藏标签。
![](https://i.imgur.com/1wHkMoL.png)

**Comment by shawncafu** [comment]
其实是想要一个更类似这样的UI，同屏显示更多的音声且以封面为主，类似DLsite视听界面和社团作品界面，或者类似的漫画/图书库管理界面
不知道怎么插图，度盘传了几个 链接: https://pan.baidu.com/s/1dD6UEEVepQWaYYLSh9U7hg 提取码: cicm 
辛苦啦
