### ISSUE TITLE
[Feature request]增加打开文件夹开关

### ISSUE THREAD

**Issue by shawncafu** [kikoeru-project/kikoeru-express#26]
起因是有很多汉化音声是mp4的形式，或者mp3+lrc的形式，在kikoeru内部听的话视频/字幕显示不出来
如果能有一个开关可以直接打开当前查看的音声所在的文件夹就方便很多啦
现在遇到这种情况我要记RJ号再去Voicework文件夹里面翻，放了几百个文件夹之后挑起来容易眼花

感谢大大！

**Comment by umonaca** [comment]
> 起因是有很多汉化音声是mp4的形式，或者mp3+lrc的形式，在kikoeru内部听的话视频/字幕显示不出来
> 如果能有一个开关可以直接打开当前查看的音声所在的文件夹就方便很多啦
> 现在遇到这种情况我要记RJ号再去Voicework文件夹里面翻，放了几百个文件夹之后挑起来容易眼花
> 
> 感谢大大！

- 外挂LRC字幕
只要LRC文件名与相应的曲目同名就可以在播放的时候同步显示出来。显示的歌词可以拖拽。不支持LRC以外的格式，并且文件名需要相同。  
![](https://i.imgur.com/hbSNkCV.png)
- MP4格式
以后可能会添加支持。
- 打开本地文件夹
这个可以考虑。但只对本地有效，也就是说比如放在Docker里面在群晖上运行是无效的。不提供在浏览器里直接浏览任意文件夹的功能，因为有安全隐患，有的人是跑在公网上的。

**Comment by umonaca** [comment]
> 起因是有很多汉化音声是mp4的形式，或者mp3+lrc的形式，在kikoeru内部听的话视频/字幕显示不出来
> 如果能有一个开关可以直接打开当前查看的音声所在的文件夹就方便很多啦
> 现在遇到这种情况我要记RJ号再去Voicework文件夹里面翻，放了几百个文件夹之后挑起来容易眼花
> 
> 感谢大大！

我想放弃这个功能。因为作为一个Web app来说安全隐患太大，任何人都有可能通过网络控制服务器执行指令。虽然可以通过各种安全机制层层把关，但总会有没想到的刁钻角度。有人是把这套程序放在公网上的。  
emby也没有这个功能，大概出于同样的理由。

如果你使用的是WIndows，推荐使用一个名叫Everything的工具，只要是NTFS文件系统，搜索任何东西都秒出结果。把它固定在任务栏，并不需要多点几次。而且即便是Windows自带的文件管理器，直接在文件夹内按文件名按键盘就可以定位到具体文件了。

**Comment by shawncafu** [comment]
感谢大大，虽然我是mac的，我找找有没有类似的软件
