### ISSUE TITLE
[Bug] 刮削含有多国语言的翻译作品时标题最后会加上「日元」

### ISSUE THREAD

**Issue by ShadowLyin** [kikoeru-project/kikoeru-express#29]
**问题描述**

刮削一些在 Dlsite 页面有多语言版本选择的作品（见截图 1）时，标题最后会多加上「日元」二字（见截图 2），不论翻译版还是原版。
**错误信息**

**版本**

 - 系统：Windows 10 20H2
 - 安装方式：Windows打包版
 - 浏览器：Chrome/Safari
 - 程序版本：v0.6.0-rc.4

**截图**

![image](https://user-images.githubusercontent.com/20549332/109514795-5bb8cc80-7ae1-11eb-8191-b8edcffe2692.png)
![image](https://user-images.githubusercontent.com/20549332/109514922-7ab75e80-7ae1-11eb-91a6-f58162ed2059.png)

**Comment by umonaca** [comment]
好问题。下一个版本会改用`og:title`作为标题。
