### ISSUE TITLE
[功能请求] 点播放器封面跳转相应作品

### ISSUE THREAD

**Issue by sallne** [kikoeru-project/kikoeru-express#42]
·兴冲冲下了发现不显示aac格式 只好打肿脸充胖子 **aac更名mp3**

·本地的情况下能一键打开相关音声的本地文件，能直接调度本地播放器就更好了
服务器整合音声这点功能就非常奈斯，但服务器端不能增幅音量，一些音声音量小的可怕

·迷你播放器 在播放时点标题/封面能返回相关音声项目
并不是很急需的功能就是操作逻辑上的问题，有时候翻着翻着音声找不回去了……能显示个RJ号也好方便搜索啊

**Comment by umonaca** [comment]
- AAC格式
如果你指的是以`.aac`为扩展名的AAC格式，将在下个版本支持。commit 23065024e0d85d85a7d351db6a0e409fd71e2bec
- 打开本地文件夹/本地文件
这是一个写起来很简单但是隐患非常大的功能，意味着任何人都可能通过网络远程控制执行任意指令。作为一个Web app来说就是这样的，我想emby出于同样的理由没有提供类似的功能。考虑到有人是把这套程序放在公网上的，所以不打算提供这个功能。详情：https://github.com/umonaca/kikoeru-express/issues/26
- 增幅音量
目前程序是不对音频文件做任何处理直接把原文件发到浏览器的，如果音量太低请首先检查一下系统音量合成器设置有没有单独对浏览器做设置。有的是社团做出来时候音量就有问题，这个确实可以通过本地播放器解决。由于前端控件不支持，暂时不打算把音量增幅加进Kikoeru。
- 点标题跳转相应项目
这个会在下个版本支持。

**Comment by sallne** [comment]
感谢解答疑惑同时维护项目也辛苦了！
