### ISSUE TITLE
[Feature request] 请求支持浏览 pdf 文件

### ISSUE THREAD

**Issue by ShadowLyin** [kikoeru-project/kikoeru-express#45]
由于有很多社团有提供 pdf 台本，目前想要看这些台本不大方便，能否支持浏览 pdf 格式的台本？

**Comment by umonaca** [comment]
可以。能否给一个编号，以便测试

**Comment by ShadowLyin** [comment]
> 可以。能否给一个编号，以便测试

好的，如 [RJ307183](https://www.dlsite.com/maniax/work/=/product_id/RJ307183.html)
如果另有需要，[Nanamori Studio](https://www.dlsite.com/maniax/circle/profile/=/maker_id/RG49502.html) 和 [しゃーぷ](https://www.dlsite.com/maniax/circle/profile/=/maker_id/RG38133.html) 这两个社团的作品基本都有附带 pdf 台本
