### ISSUE TITLE
[Bug] 应当跳过没有权限访问的文件夹

### ISSUE THREAD

**Issue by MoeKagari** [kikoeru-project/kikoeru-express#46]
![屏幕截图 2021-03-23 222910](https://user-images.githubusercontent.com/17805261/112162655-35d9a000-8c27-11eb-84ab-08d1355bb9da.png)
看了一下音声的页面，和其他相比，少了评价这一项数据(NULL)，是这个原因？

**Comment by MoeKagari** [comment]
顺便问一下，添加本地音声库时，音声在根目录D盘，绝对路径写成D:或D:\都不行，应该写成什么？

**Comment by MoeKagari** [comment]
原来路径没写错，而是程序会去扫描D:\System Volume Information这个文件夹导致错误
![网页捕获_23-3-2021_224053_localhost](https://user-images.githubusercontent.com/17805261/112164435-d7152600-8c28-11eb-8475-ee37b28e0a60.jpeg)

**Comment by umonaca** [comment]
问题1是已知问题，commit 62b7a9934a6dbdab9c2bc3af5c5b48753db354a3 已经修复，下一个版本发布时解决。  
问题2可以下个版本解决。

**Comment by MoeKagari** [comment]
> 问题1是已知问题，commit [62b7a99](https://github.com/kikoeru-project/kikoeru-express/commit/62b7a9934a6dbdab9c2bc3af5c5b48753db354a3) 已经修复，下一个版本发布时解决。
> 问题2可以下个版本解决。

好的，感谢解答&项目维护辛苦了
