### ISSUE TITLE
[Feature request] 希望添加区分R18和全年龄作品的标记

### ISSUE THREAD

**Issue by momo-s07** [kikoeru-project/kikoeru-express#49]

**Comment by umonaca** [comment]
已经有一个“按全年龄作品排序”的选项了。的确是可以单独加一个按钮，就是手机上有点拥挤，我想想怎么改

**Comment by momo-s07** [comment]
> 已经有一个“按全年龄作品排序”的选项了。的确是可以单独加一个按钮，就是手机上有点拥挤，我想想怎么改

我觉得可以在封面上，RJ号旁边添加标记

**Comment by momo-s07** [comment]
> 已经有一个“按全年龄作品排序”的选项了。的确是可以单独加一个按钮，就是手机上有点拥挤，我想想怎么改

按照全年龄新作优先的顺序，点了之后没有变化

**Comment by umonaca** [comment]
> > 已经有一个“按全年龄作品排序”的选项了。的确是可以单独加一个按钮，就是手机上有点拥挤，我想想怎么改
> 
> 按照全年龄新作优先的顺序，点了之后没有变化

如果你说的是一个网站的话，那个网站是有这个问题，但kikoeru没有见过这个问题。

**Comment by umonaca** [comment]
> > 已经有一个“按全年龄作品排序”的选项了。的确是可以单独加一个按钮，就是手机上有点拥挤，我想想怎么改
> 
> 按照全年龄新作优先的顺序，点了之后没有变化

重现不出来，你说的是那个网站还是kikoeru？那个网站的话，由于作品数量太多，你点了之后是要等一下才出来的。

**Comment by umonaca** [comment]
> > 已经有一个“按全年龄作品排序”的选项了。的确是可以单独加一个按钮，就是手机上有点拥挤，我想想怎么改
> 
> 按照全年龄新作优先的顺序，点了之后没有变化

已确认是DLsite改版导致的，改版导致爬虫判断错误。会在下个版本修复这个问题。

**Comment by umonaca** [comment]
发现一个问题：DLsite的作品是分三个年龄等级的：全年龄，R-15，18禁。你们认为R-15适合划到全年龄区吗？还是说搞成3个年龄等级比较合适？

**Comment by ShadowLyin** [comment]
> 发现一个问题：DLsite的作品是分三个年龄等级的：全年龄，R-15，18禁。你们认为R-15适合划到全年龄区吗？还是说搞成3个年龄等级比较合适？

个人比较倾向于将 R-15 划分到全年龄，因为对我来说全年龄与 R-15 都可以用于睡眠。
不过 Dlsite 是将 R-15 划分到了 R-18 分区，个人认为可能是出于保守考虑，防止有青少年浏览到不合适的内容。

**Comment by umonaca** [comment]
那就先按R-15算全年龄这样搞了。
