### ISSUE TITLE
[Feature request] 希望增加按扫描文件添加时间排序和文件夹创建时间排序

### ISSUE THREAD

**Issue by DoraZed** [kikoeru-project/kikoeru-express#66]
添加的新文件会混入大量已有的内容中难以查找，按找添加时间排序可以方便地看到新增内容。
I hope to add a feature sorting by adding time and by folder creation (or modify) time, for new content can be easily seen.

**Comment by umonaca** [comment]
与#34 重复，会在下个版本支持
