### ISSUE TITLE
[Bug] 扫描时程序总是崩溃

### ISSUE THREAD

**Issue by lisansas** [kikoeru-project/kikoeru-express#70]
**问题描述**

如题 而且发生频率极高 出现错误信息后程序直接闪退

**错误信息**
internal/child_process.js:406
    throw errnoException(err, 'spawn');
    ^

Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:406:11)
    at Object.spawn (child_process.js:548:9)
    at Object.spawn (pkg/prelude/bootstrap.js:1588:27)
    at Object.fork (child_process.js:116:25)
    at Socket.<anonymous> (D:\snapshot\kikoeru-express\socket.js)
    at Socket.emit (events.js:315:20)
    at D:\snapshot\kikoeru-express\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'spawn'

**版本**

 - 系统： win10
 - 安装方式：Windows打包版
 - 浏览器： ALL
 - 程序版本：v0.6.2

**截图**

**Comment by cha0sCat** [comment]
试试在运行主程序的时候使用 右键-以管理员权限执行

**Comment by umonaca** [comment]
除非有第二个人报告类似的情况，否则不打算解决这个问题。  
这个错误提示的意思是“创建子进程时被操作系统拒绝”。具体来讲，用户使用扫描功能的时候程序会创建一个扫描子进程，以避免CPU负荷高的扫描过程阻塞主进程（其实是可以做成Node.js Worker threads不过改起来太麻烦了）。正常情况下这个程序并不需要管理员权限，但是Windows环境太脏，比如说装了莫名其妙的杀毒软件，或者数字公司的全家桶之类的都有可能导致这个过程失败。这种问题没法改代码解决，也没法通过GitHub留言解决。

**Comment by lisansas** [comment]
> 除非有第二个人报告类似的情况，否则不打算解决这个问题。
> 这个错误提示的意思是“创建子进程时被操作系统拒绝”。具体来讲，用户使用扫描功能的时候程序会创建一个扫描子进程，以避免CPU负荷高的扫描过程阻塞主进程（其实是可以做成Node.js Worker threads不过改起来太麻烦了）。正常情况下这个程序并不需要管理员权限，但是Windows环境太脏，比如说装了莫名其妙的杀毒软件，或者数字公司的全家桶之类的都有可能导致这个过程失败。这种问题没法改代码解决，也没法通过GitHub留言解决。

没事 我测试了几天管理员运行 没有再发生了 应该和杀毒软件之类的没关系 毕竟我电脑裸奔的  连Microsoft defender都没开 不过也是很多年没重装过电脑了 可能是其他什么玩意的残留吧 感谢解决。
